### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by SebastienMorais** [SebastienMorais/rpg-game#25]
Liste de proposition de modifications pour l'an prochain :

- [ ] update le fichier README pour être plus simple / claire
- [ ] ajouter un diagramme UML pour illustrer les intéractions entre classes
- [ ] retirer l'itérateur de la classe team ?
- [ ] découper le sujet en parties, e.g. I) classes unités (alliés / ennemis) II) classes team (alliés / ennemis) III) class Game & méthodes
